disable the second call EnableAsync
aliyun/alibaba-cloud-sdk-go pull request #467
Opened 2020-11-19 02:10 UTC by wenzuochao

2020-11-19 06:28 UTC, JacksonTian commented on sdk/client.go
> +		client.isOpenAsync = false
这个为啥要加

2020-11-19 06:28 UTC, JacksonTian requested changes
SMC

2020-11-19 06:48 UTC, JacksonTian requested changes
SMC

2020-11-19 09:15 UTC, wenzuochao commented on sdk/client.go
> +		client.isOpenAsync = false
这里调用了 EnableAsync ，会把 isOpenAsync改为 true，导致用户在外部调用 EnableAsync不生效，这个感觉会出问题，因为用户在初始化的时候，可能没传 config.GoRoutinePoolSize, config.MaxTaskQueueSize，导致没启动协程，如果这里不把 isOpenAsync = false，用户只能先shutdown，在EnableAsync，感觉不太好，而且会有不兼容

2020-11-23 02:34 UTC, JacksonTian approved these changes

2020-11-23 05:09 UTC, merged